FROM opensuse:42.1
MAINTAINER Antony Messerli <amesserl@rackspace.com>

# Add a directory to hold our chroot
RUN mkdir /tmp/bootstrap

# Add Repositories
RUN zypper --root /tmp/bootstrap ar http://mirror.rackspace.com/opensuse/distribution/leap/42.1/repo/oss/ repo-oss

CMD ["zypper", "-n", "--gpg-auto-import-keys", "--root", "/tmp/bootstrap", "install", "rpm", "zypper", "wget", "vim", "systemd"]
