#!/bin/bash

if [ ! -f /persist/etc/xensource-inventory ]; then
        CONTROL_DOMAIN_UUID=`uuidgen`
        INSTALLATION_UUID=`uuidgen`
        INSTALLATION_DATE=`date`
        cat > /persist/etc/xensource-inventory <<EOF
PRIMARY_DISK='/dev/sda'
PRODUCT_VERSION='6.6.80'
DOM0_VCPUS='1'
CONTROL_DOMAIN_UUID='$CONTROL_DOMAIN_UUID'
DOM0_MEM='752'
XEN_VERSION='4.5.0'
COMPANY_NAME_SHORT='Citrix'
KERNEL_VERSION='3.10.71'
MANAGEMENT_ADDRESS_TYPE='IPv4'
PRODUCT_VERSION_TEXT='6.6'
PRODUCT_BRAND='XenServer'
LINUX_KABI_VERSION='3.10.0+0'
INSTALLATION_UUID='$INSTALLATION_UUID'
PRODUCT_VERSION_TEXT_SHORT='6.6'
BRAND_CONSOLE='XenCenter'
PRODUCT_NAME='xenenterprise'
MANAGEMENT_INTERFACE='xenbr0'
PLATFORM_VERSION='2.0.0'
BUILD_NUMBER='100820c'
PLATFORM_NAME='XCP'
BACKUP_PARTITION='/dev/sda2'
INSTALLATION_DATE='2015-06-01 11:44:32.909949'
COMPANY_NAME='Citrix Systems, Inc.'
EOF
fi

# Create xensource-inventory symlink
rm /etc/xensource-inventory
ln -s /persist/etc/xensource-inventory /etc/xensource-inventory
     
